// ---------------------------------------------------------------------------
// EasyChip Playground — stub content generators
// Each function returns a realistic, syntactically-correct file as a string.
// ---------------------------------------------------------------------------

import { SPEC_CATEGORIES, getOptionById } from "./spec-options";

// ---- helpers ---------------------------------------------------------------

const HEADER = "// Generated by EasyChip Playground — Q3 2026";

function opt(specs: Record<string, string>, catId: string): string {
  return specs[catId] ?? "";
}

function resetSignal(specs: Record<string, string>): {
  name: string;
  activeLow: boolean;
  async: boolean;
  hasReset: boolean;
} {
  const ck = opt(specs, "clock_reset");
  if (ck === "no_reset")
    return { name: "", activeLow: false, async: false, hasReset: false };
  const activeLow = ck !== "sync_active_high";
  const async = ck === "async_active_low" || ck === "dual_clock";
  const name = activeLow ? "rst_n" : "rst";
  return { name, activeLow, async, hasReset: true };
}

function parameterList(specs: Record<string, string>): string[] {
  const p = opt(specs, "parameters");
  const map: Record<string, string[]> = {
    std_8bit: ["parameter DATA_WIDTH = 8", "parameter ADDR_WIDTH = 16"],
    std_32bit: ["parameter DATA_WIDTH = 32", "parameter ADDR_WIDTH = 32"],
    buffered: ["parameter DATA_WIDTH = 8", "parameter DEPTH = 256"],
    serial: ["parameter BAUD_DIV = 868", "parameter DATA_WIDTH = 8"],
    multi_channel: [
      "parameter NUM_CHANNELS = 4",
      "parameter RESOLUTION = 12",
    ],
  };
  return map[p] ?? ["parameter DATA_WIDTH = 8"];
}

function portLines(specs: Record<string, string>): string[] {
  const iface = opt(specs, "interface_ports");
  const rst = resetSignal(specs);
  const common = ["  input  wire clk,"];
  if (rst.hasReset) common.push(`  input  wire ${rst.name},`);

  const portMap: Record<string, string[]> = {
    minimal: [
      "  input  wire [DATA_WIDTH-1:0] data_in,",
      "  output reg  [DATA_WIDTH-1:0] data_out,",
      "  input  wire valid,",
      "  output reg  ready",
    ],
    standard: [
      "  input  wire [7:0] data_in,",
      "  output reg  [7:0] data_out,",
      "  input  wire wr_en,",
      "  input  wire rd_en,",
      "  output reg  busy,",
      "  output reg  done",
    ],
    bus_interface: [
      "  // Write address channel",
      "  input  wire [ADDR_WIDTH-1:0] s_axi_awaddr,",
      "  input  wire                  s_axi_awvalid,",
      "  output reg                   s_axi_awready,",
      "  // Write data channel",
      "  input  wire [DATA_WIDTH-1:0] s_axi_wdata,",
      "  input  wire                  s_axi_wvalid,",
      "  output reg                   s_axi_wready,",
      "  // Write response channel",
      "  output reg  [1:0]            s_axi_bresp,",
      "  output reg                   s_axi_bvalid,",
      "  input  wire                  s_axi_bready,",
      "  // Read address channel",
      "  input  wire [ADDR_WIDTH-1:0] s_axi_araddr,",
      "  input  wire                  s_axi_arvalid,",
      "  output reg                   s_axi_arready,",
      "  // Read data channel",
      "  output reg  [DATA_WIDTH-1:0] s_axi_rdata,",
      "  output reg  [1:0]            s_axi_rresp,",
      "  output reg                   s_axi_rvalid,",
      "  input  wire                  s_axi_rready",
    ],
    streaming: [
      "  input  wire [DATA_WIDTH-1:0] s_axis_tdata,",
      "  input  wire                  s_axis_tvalid,",
      "  output reg                   s_axis_tready,",
      "  input  wire                  s_axis_tlast,",
      "  output reg  [DATA_WIDTH-1:0] m_axis_tdata,",
      "  output reg                   m_axis_tvalid,",
      "  input  wire                  m_axis_tready,",
      "  output reg                   m_axis_tlast",
    ],
    memory_mapped: [
      "  input  wire [ADDR_WIDTH-1:0] addr,",
      "  input  wire [DATA_WIDTH-1:0] wdata,",
      "  output reg  [DATA_WIDTH-1:0] rdata,",
      "  input  wire we,",
      "  input  wire re,",
      "  input  wire cs",
    ],
  };

  const selected = portMap[iface] ?? portMap.minimal!;
  return [...common, ...selected];
}

function clockPeriodNs(specs: Record<string, string>): number {
  const t = opt(specs, "timing");
  const map: Record<string, number> = {
    "50mhz": 20.0,
    "100mhz": 10.0,
    "200mhz": 5.0,
    "10mhz": 100.0,
    freq_agnostic: 10.0,
  };
  return map[t] ?? 10.0;
}

function freqLabel(specs: Record<string, string>): string {
  const t = opt(specs, "timing");
  const map: Record<string, string> = {
    "50mhz": "50 MHz",
    "100mhz": "100 MHz",
    "200mhz": "200 MHz",
    "10mhz": "10 MHz",
    freq_agnostic: "Frequency-agnostic",
  };
  return map[t] ?? "100 MHz";
}

// ---- public generators -----------------------------------------------------

export function generateVerilogStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const params = parameterList(specs);
  const ports = portLines(specs);
  const rst = resetSignal(specs);
  const behaviour = opt(specs, "functional_behaviour");

  const paramBlock =
    params.length > 0
      ? ` #(\n${params.map((p) => `  ${p}`).join(",\n")}\n)`
      : "";

  // Ensure last port line has no trailing comma
  const portBlock = ports
    .map((line, i) => {
      if (i === ports.length - 1) return line.replace(/,\s*$/, "");
      return line;
    })
    .join("\n");

  const resetCondition = rst.hasReset
    ? rst.activeLow
      ? `!${rst.name}`
      : rst.name
    : null;
  const sensitivity =
    rst.async && rst.hasReset
      ? `posedge clk or ${rst.activeLow ? "negedge" : "posedge"} ${rst.name}`
      : "posedge clk";

  let body: string;

  if (behaviour === "fsm_linear" || behaviour === "fsm_multi_branch") {
    const states =
      behaviour === "fsm_linear"
        ? ["IDLE", "ACTIVE", "DONE"]
        : ["IDLE", "SETUP", "READ", "WRITE", "ERROR"];
    const stateWidth = states.length > 4 ? 3 : 2;
    const stateEnc = states
      .map((s, i) => `  localparam S_${s} = ${stateWidth}'d${i};`)
      .join("\n");
    const stateReg = `  reg [${stateWidth - 1}:0] state, next_state;\n`;
    const resetBlock = resetCondition
      ? `    if (${resetCondition}) begin\n      state <= S_${states[0]};\n    end else begin\n      state <= next_state;\n    end`
      : `    state <= next_state;`;

    body = [
      stateEnc,
      "",
      stateReg,
      `  always @(${sensitivity}) begin`,
      resetBlock,
      "  end",
      "",
      "  always @(*) begin",
      "    next_state = state;",
      "    case (state)",
      ...states.map(
        (s) =>
          `      S_${s}: begin\n        // TODO: Implementation\n      end`,
      ),
      "      default: next_state = S_" + states[0] + ";",
      "    endcase",
      "  end",
    ].join("\n");
  } else if (behaviour === "shift_register") {
    const resetBlock = resetCondition
      ? `    if (${resetCondition}) begin\n      shift_reg <= {DATA_WIDTH{1'b0}};\n    end else begin\n      // TODO: Implementation — parallel load or shift\n      shift_reg <= {shift_reg[DATA_WIDTH-2:0], 1'b0};\n    end`
      : `    // TODO: Implementation — parallel load or shift\n    shift_reg <= {shift_reg[DATA_WIDTH-2:0], 1'b0};`;
    body = [
      "  reg [DATA_WIDTH-1:0] shift_reg;",
      "",
      `  always @(${sensitivity}) begin`,
      resetBlock,
      "  end",
    ].join("\n");
  } else if (behaviour === "pipeline") {
    const resetBlock = resetCondition
      ? `    if (${resetCondition}) begin\n      stage1_valid <= 1'b0;\n      stage2_valid <= 1'b0;\n    end else begin\n      // TODO: Implementation — pipeline advancement\n      stage1_valid <= valid;\n      stage2_valid <= stage1_valid;\n    end`
      : `    // TODO: Implementation — pipeline advancement\n    stage1_valid <= valid;\n    stage2_valid <= stage1_valid;`;
    body = [
      "  reg [DATA_WIDTH-1:0] stage1_data, stage2_data;",
      "  reg stage1_valid, stage2_valid;",
      "",
      `  always @(${sensitivity}) begin`,
      resetBlock,
      "  end",
    ].join("\n");
  } else if (behaviour === "counter") {
    const overflow = opt(specs, "edge_cases");
    const wrapLogic =
      overflow === "overflow_saturate"
        ? "      if (count == {DATA_WIDTH{1'b1}})\n        overflow <= 1'b1;\n      else\n        count <= count + 1'b1;"
        : "      count <= count + 1'b1; // wraps naturally";
    const resetBlock = resetCondition
      ? `    if (${resetCondition}) begin\n      count <= {DATA_WIDTH{1'b0}};\n    end else begin\n${wrapLogic}\n    end`
      : wrapLogic;
    const extraRegs =
      overflow === "overflow_saturate" ? "  reg overflow;\n" : "";
    body = [
      "  reg [DATA_WIDTH-1:0] count;",
      extraRegs,
      `  always @(${sensitivity}) begin`,
      resetBlock,
      "  end",
    ].join("\n");
  } else {
    body = [
      "  // TODO: Implementation",
      `  always @(${sensitivity}) begin`,
      resetCondition
        ? `    if (${resetCondition}) begin\n      // reset outputs\n    end else begin\n      // TODO: Implementation\n    end`
        : "    // TODO: Implementation",
      "  end",
    ].join("\n");
  }

  return [
    HEADER,
    `module ${moduleName}${paramBlock} (`,
    portBlock,
    ");",
    "",
    body,
    "",
    "endmodule",
    "",
  ].join("\n");
}

export function generateSVStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const params = parameterList(specs);
  const rst = resetSignal(specs);

  const paramNames = params.map((p) =>
    p.replace(/parameter\s+/, "").split("=")[0]!.trim(),
  );

  const paramBlockLines =
    params.length > 0
      ? ["#(", ...params.map((p, i) => `  ${p}${i < params.length - 1 ? "," : ""}`), ")"]
      : [];

  const instParamLines =
    params.length > 0
      ? paramNames.map(
          (n, i) => `    .${n}(${n})${i < paramNames.length - 1 ? "," : ""}`,
        )
      : [];

  const lines: string[] = [
    HEADER,
    `// SystemVerilog wrapper / verification harness for ${moduleName}`,
    "",
    `module ${moduleName}_sv`,
    ...paramBlockLines,
    "(",
    "  input  logic clk,",
  ];

  if (rst.hasReset) lines.push(`  input  logic ${rst.name},`);

  lines.push(
    "  input  logic [DATA_WIDTH-1:0] data_in,",
    "  output logic [DATA_WIDTH-1:0] data_out",
    ");",
    "",
    `  ${moduleName} #(`,
    ...instParamLines,
    "  ) u_dut (",
    "    .clk(clk),",
  );

  if (rst.hasReset) lines.push(`    .${rst.name}(${rst.name}),`);

  lines.push(
    "    .data_in(data_in),",
    "    .data_out(data_out)",
    "  );",
    "",
    "  // TODO: Add assertions and coverage",
    "",
    "endmodule",
    "",
  );

  return lines.join("\n");
}

export function generatePackageStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const params = parameterList(specs);

  return [
    HEADER,
    `package ${moduleName}_pkg;`,
    "",
    ...params.map((p) => {
      const parts = p.replace("parameter ", "").split("=");
      const name = parts[0]!.trim();
      const val = parts[1]!.trim();
      return `  localparam int ${name} = ${val};`;
    }),
    "",
    "  // Derived parameters",
    "  localparam int BYTE_COUNT = DATA_WIDTH / 8;",
    "",
    "  // Common type definitions",
    "  typedef logic [DATA_WIDTH-1:0] data_t;",
    "",
    "endpackage",
    "",
  ].join("\n");
}

export function generateTestbenchStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const period = clockPeriodNs(specs);
  const rst = resetSignal(specs);

  const assertReset = rst.hasReset
    ? rst.activeLow
      ? "    dut.rst_n.value = 0"
      : "    dut.rst.value = 1"
    : "    # No reset signal — skip";

  const deassertReset = rst.hasReset
    ? rst.activeLow
      ? "    dut.rst_n.value = 1"
      : "    dut.rst.value = 0"
    : "    pass";

  return [
    `# ${HEADER.replace("// ", "")}`,
    `# cocotb testbench for ${moduleName}`,
    "",
    "import cocotb",
    "from cocotb.clock import Clock",
    "from cocotb.triggers import RisingEdge, Timer",
    "",
    "",
    "@cocotb.test()",
    `async def test_${moduleName}_reset(dut):`,
    '    """Verify reset behaviour."""',
    `    clock = Clock(dut.clk, ${period}, units="ns")`,
    "    cocotb.start_soon(clock.start())",
    "",
    "    # Assert reset",
    assertReset,
    "    await RisingEdge(dut.clk)",
    "    await RisingEdge(dut.clk)",
    "",
    "    # De-assert reset",
    deassertReset,
    "    await RisingEdge(dut.clk)",
    "",
    "    # TODO: Add functional checks",
    `    dut._log.info("Reset test passed")`,
    "",
    "",
    "@cocotb.test()",
    `async def test_${moduleName}_basic(dut):`,
    '    """Basic functional test."""',
    `    clock = Clock(dut.clk, ${period}, units="ns")`,
    "    cocotb.start_soon(clock.start())",
    "",
    "    # De-assert reset",
    deassertReset,
    "    for _ in range(5):",
    "        await RisingEdge(dut.clk)",
    "",
    "    # TODO: Drive stimulus and check outputs",
    `    dut._log.info("Basic test passed")`,
    "",
  ].join("\n");
}

export function generateMakefileStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  return [
    `# ${HEADER.replace("// ", "")}`,
    `# Makefile for cocotb simulation of ${moduleName}`,
    "",
    "TOPLEVEL_LANG = verilog",
    "SIM ?= icarus",
    "",
    `VERILOG_SOURCES = $(PWD)/../src/${moduleName}.v`,
    `TOPLEVEL = ${moduleName}`,
    `MODULE = test_${moduleName}`,
    "",
    "include $(shell cocotb-config --makefiles)/Makefile.sim",
    "",
  ].join("\n");
}

export function generateYosysScript(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const tech = opt(specs, "target_tech");
  let readLib: string;
  let synthCmd: string;

  switch (tech) {
    case "sky130":
      readLib = "read_liberty -lib sky130_fd_sc_hd__tt_025C_1v80.lib";
      synthCmd = "synth -top " + moduleName;
      break;
    case "gf180":
      readLib =
        "read_liberty -lib gf180mcu_fd_sc_mcu7t5v0__tt_025C_1v80.lib";
      synthCmd = "synth -top " + moduleName;
      break;
    case "xilinx_7series":
      readLib = "# Vivado flow — no liberty file needed";
      synthCmd = "synth_xilinx -top " + moduleName + " -family xc7";
      break;
    case "intel_cyclone_v":
      readLib = "# Quartus flow — no liberty file needed";
      synthCmd = "synth_intel_alm -top " + moduleName + " -family cyclonev";
      break;
    default:
      readLib = "# Technology-agnostic — no liberty file";
      synthCmd = "synth -top " + moduleName;
      break;
  }

  const isAsicTarget = tech === "sky130" || tech === "gf180";
  const libFile =
    tech === "sky130"
      ? "sky130_fd_sc_hd__tt_025C_1v80.lib"
      : "gf180mcu_fd_sc_mcu7t5v0__tt_025C_1v80.lib";

  const techMapping = isAsicTarget
    ? `dfflibmap -liberty ${libFile}\nabc -liberty ${libFile}`
    : "# No liberty-based mapping for this target";

  return [
    `# ${HEADER.replace("// ", "")}`,
    `# Yosys synthesis script for ${moduleName}`,
    "",
    `read_verilog ../src/${moduleName}.v`,
    readLib,
    "",
    "# Elaborate",
    "hierarchy -check -top " + moduleName,
    "",
    "# Synthesis",
    "proc; opt; fsm; opt; memory; opt",
    synthCmd,
    "",
    "# Technology mapping",
    techMapping,
    "",
    "# Clean up",
    "clean",
    "",
    "# Reports",
    "stat",
    `write_verilog -noattr ${moduleName}_synth.v`,
    "",
  ].join("\n");
}

export function generateSDCStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const period = clockPeriodNs(specs);
  const freq = freqLabel(specs);
  const clkReset = opt(specs, "clock_reset");
  const isDualClock = clkReset === "dual_clock";
  const rst = resetSignal(specs);

  const lines: string[] = [
    `# ${HEADER.replace("// ", "")}`,
    `# SDC timing constraints for ${moduleName}`,
    `# Target: ${freq}`,
    "",
    `create_clock -name clk -period ${period.toFixed(1)} [get_ports clk]`,
  ];

  if (isDualClock) {
    lines.push(
      `create_clock -name clk_b -period ${(period * 1.5).toFixed(1)} [get_ports clk_b]`,
      "",
      "# Clock domain crossing",
      "set_clock_groups -asynchronous -group {clk} -group {clk_b}",
    );
  }

  lines.push(
    "",
    "# Input / output delays",
    `set_input_delay  -clock clk ${(period * 0.2).toFixed(1)} [all_inputs]`,
    `set_output_delay -clock clk ${(period * 0.2).toFixed(1)} [all_outputs]`,
    "",
    "# False paths on reset",
    rst.hasReset
      ? `set_false_path -from [get_ports ${rst.name}]`
      : "# No reset signal — no false path needed",
    "",
  );

  return lines.join("\n");
}

export function generateSpecDoc(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const lines: string[] = [
    `# ${moduleName} — Specification`,
    "",
    "> Generated by EasyChip Playground — Q3 2026",
    "",
    "## Selected Specifications",
    "",
  ];

  for (const cat of SPEC_CATEGORIES) {
    const selectedId = specs[cat.id];
    const option = selectedId ? getOptionById(cat.id, selectedId) : undefined;
    lines.push(
      `### Spec ${cat.number}: ${cat.title}`,
      "",
      option
        ? `**${option.label}** — ${option.description}`
        : "_Not specified_",
      "",
    );
  }

  lines.push(
    "## Notes",
    "",
    "- All signals active-high unless otherwise noted.",
    "- Parameters can be overridden at instantiation.",
    "- See README.md for build and simulation instructions.",
    "",
  );

  return lines.join("\n");
}

export function generateReadme(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const techOpt = getOptionById("target_tech", opt(specs, "target_tech"));
  const modOpt = getOptionById("module_type", opt(specs, "module_type"));

  return [
    `# ${moduleName}`,
    "",
    modOpt
      ? `> ${modOpt.label} — ${modOpt.description}`
      : "> EasyChip generated project",
    "",
    "Generated by **EasyChip Playground — Q3 2026**.",
    "",
    "## Directory Structure",
    "",
    "```",
    "├── src/         # RTL source files",
    "├── tb/          # Testbenches (cocotb / Python)",
    "├── syn/         # Synthesis scripts & constraints",
    "└── docs/        # Documentation",
    "```",
    "",
    "## Quick Start",
    "",
    "### Simulation",
    "",
    "```bash",
    "cd tb",
    "make",
    "```",
    "",
    "### Synthesis",
    "",
    techOpt
      ? `Target: **${techOpt.label}** (${techOpt.description})`
      : "Target: generic synthesis",
    "",
    "```bash",
    "cd syn",
    "yosys -s synth.ys",
    "```",
    "",
    "## Specification Summary",
    "",
    "See [docs/spec.md](docs/spec.md) for full specification details.",
    "",
  ].join("\n");
}

export function generateMemoryStub(
  specs: Record<string, string>,
  moduleName: string,
): string {
  const mem = opt(specs, "memory");
  const rst = resetSignal(specs);
  const sensitivity =
    rst.async && rst.hasReset
      ? `posedge clk or ${rst.activeLow ? "negedge" : "posedge"} ${rst.name}`
      : "posedge clk";
  const resetCond = rst.hasReset
    ? rst.activeLow
      ? `!${rst.name}`
      : rst.name
    : null;

  if (mem === "register_file") {
    const lines: string[] = [
      HEADER,
      `module ${moduleName}_regfile #(`,
      "  parameter DATA_WIDTH = 8,",
      "  parameter NUM_REGS   = 16,",
      "  parameter ADDR_BITS  = $clog2(NUM_REGS)",
      ") (",
      "  input  wire                  clk,",
    ];
    if (rst.hasReset)
      lines.push(`  input  wire                  ${rst.name},`);
    lines.push(
      "  input  wire [ADDR_BITS-1:0]  wr_addr,",
      "  input  wire [DATA_WIDTH-1:0] wr_data,",
      "  input  wire                  wr_en,",
      "  input  wire [ADDR_BITS-1:0]  rd_addr,",
      "  output reg  [DATA_WIDTH-1:0] rd_data",
      ");",
      "",
      "  reg [DATA_WIDTH-1:0] regs [0:NUM_REGS-1];",
      "",
      "  // Write port",
      `  always @(${sensitivity}) begin`,
    );
    if (resetCond) {
      lines.push(
        `    if (${resetCond}) begin`,
        "      // TODO: Optional reset of register file",
        "    end else if (wr_en) begin",
      );
    } else {
      lines.push("    if (wr_en) begin");
    }
    lines.push(
      "      regs[wr_addr] <= wr_data;",
      "    end",
      "  end",
      "",
      "  // Read port (asynchronous)",
      "  always @(*) begin",
      "    rd_data = regs[rd_addr];",
      "  end",
      "",
      "endmodule",
      "",
    );
    return lines.join("\n");
  }

  if (mem === "shift_reg") {
    const lines: string[] = [
      HEADER,
      `module ${moduleName}_shiftreg #(`,
      "  parameter WIDTH = 8",
      ") (",
      "  input  wire             clk,",
    ];
    if (rst.hasReset)
      lines.push(`  input  wire             ${rst.name},`);
    lines.push(
      "  input  wire             shift_en,",
      "  input  wire             load,",
      "  input  wire [WIDTH-1:0] par_in,",
      "  output wire             ser_out",
      ");",
      "",
      "  reg [WIDTH-1:0] sr;",
      "",
      `  always @(${sensitivity}) begin`,
    );
    if (resetCond) {
      lines.push(
        `    if (${resetCond})`,
        "      sr <= {WIDTH{1'b0}};",
        "    else if (load)",
      );
    } else {
      lines.push("    if (load)");
    }
    lines.push(
      "      sr <= par_in;",
      "    else if (shift_en)",
      "      sr <= {sr[WIDTH-2:0], 1'b0};",
      "  end",
      "",
      "  assign ser_out = sr[WIDTH-1];",
      "",
      "endmodule",
      "",
    );
    return lines.join("\n");
  }

  if (mem === "single_port_sram") {
    return [
      HEADER,
      `module ${moduleName}_sram #(`,
      "  parameter DATA_WIDTH = 8,",
      "  parameter DEPTH      = 256,",
      "  parameter ADDR_WIDTH = $clog2(DEPTH)",
      ") (",
      "  input  wire                  clk,",
      "  input  wire [ADDR_WIDTH-1:0] addr,",
      "  input  wire [DATA_WIDTH-1:0] wdata,",
      "  output reg  [DATA_WIDTH-1:0] rdata,",
      "  input  wire                  we",
      ");",
      "",
      "  reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];",
      "",
      "  always @(posedge clk) begin",
      "    if (we)",
      "      mem[addr] <= wdata;",
      "    rdata <= mem[addr];",
      "  end",
      "",
      "endmodule",
      "",
    ].join("\n");
  }

  if (mem === "dual_port_sram") {
    return [
      HEADER,
      `module ${moduleName}_dpram #(`,
      "  parameter DATA_WIDTH = 8,",
      "  parameter DEPTH      = 256,",
      "  parameter ADDR_WIDTH = $clog2(DEPTH)",
      ") (",
      "  input  wire                  clk_a,",
      "  input  wire [ADDR_WIDTH-1:0] addr_a,",
      "  input  wire [DATA_WIDTH-1:0] wdata_a,",
      "  output reg  [DATA_WIDTH-1:0] rdata_a,",
      "  input  wire                  we_a,",
      "  input  wire                  clk_b,",
      "  input  wire [ADDR_WIDTH-1:0] addr_b,",
      "  input  wire [DATA_WIDTH-1:0] wdata_b,",
      "  output reg  [DATA_WIDTH-1:0] rdata_b,",
      "  input  wire                  we_b",
      ");",
      "",
      "  reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];",
      "",
      "  // Port A",
      "  always @(posedge clk_a) begin",
      "    if (we_a)",
      "      mem[addr_a] <= wdata_a;",
      "    rdata_a <= mem[addr_a];",
      "  end",
      "",
      "  // Port B",
      "  always @(posedge clk_b) begin",
      "    if (we_b)",
      "      mem[addr_b] <= wdata_b;",
      "    rdata_b <= mem[addr_b];",
      "  end",
      "",
      "endmodule",
      "",
    ].join("\n");
  }

  // Fallback (no_storage)
  return [
    HEADER,
    `// No memory module required for ${moduleName} (pure combinational).`,
    "",
  ].join("\n");
}
